### ISSUE TITLE
Custom log location

### ISSUE THREAD

**Issue by magikid** [linuxserver/docker-deluge#120]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I could provide an environment variable to the location of my logfile.

## Current Behavior

Currently, it's hardcoded to `/config/deluged.log`

## Alternatives Considered

I've read through the deluge documentation and from what I could find, the only place you can specify the log location is on the command line when starting the process.

**Comment by pyrodex** [comment]
This change has now broken ALL logging in Deluge. While it is in the docker container it doesn't persist past restarts. Why don't you restore the feature of logging output and add an ENV to make it to a file?

**Comment by thelamer** [comment]
Docker logging has more control than you think here: 
https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers
journald is what I recommend for you. 
This was a calculated decision, for every x user that wants a proprietary log location there are 100x that want it in their docker output, we get many complaints about what is this huge file in my config mount, and when fielding support we generally only ever get docker logs from users. All application output in all cases across our containers should dump to docker logs otherwise we are trapped into maintaining log rotate layers on top of just the core application. The only exception to this rule currently is our NGINX baseimage which again a calculated decision as there are many log files from PHP/NGINX that need to be logically separated.
