### ISSUE TITLE
Docker image increased size in latest release

### ISSUE THREAD

**Issue by ngosang** [linuxserver/docker-deluge#149]
![Screenshot_2022-06-29-00-06-13-15_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/10577978/176308669-7c2d24c7-201b-4164-b8ae-9b7a3efa10b7.jpg)

**Comment by j0nnymoe** [comment]
Yes it has increased by 9MB as it looks like it had a rebase 12 days ago and also it was an extra r release. Though please note it actually decreased in size since 4 months ago.

As you have just posted a screenshot of the image showing the image sizes without any context to why you've opened this issue or even provided a question, I'm going to mark this invalid until something is provided.
